name: blog_app
description: A Fluser web application
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluser: 
    path: /Users/kiddo/Documents/fluser-framework
  provider: ^6.0.5
  go_router: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
